### ISSUE TITLE
Question permission to start calls

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [nuclearfog/Apollo-Music#1]
![apollo](https://user-images.githubusercontent.com/61406324/141656844-6821f34d-6905-48c5-8275-a8479af36854.jpg)
Why need this app the permission to start calls?

**Comment by nuclearfog** [comment]
This permission is used to reduce music volume when receiving a phone call. For newer Android versions it isn't required  anymore, so I will remove this in the next release.
