### ISSUE TITLE
Smaller scrollbar touch zone

### ISSUE THREAD

**Issue by Cwpute** [nuclearfog/Apollo-Music#17]
I find the scrollbar touch zone to be very big ! in the album view, it takes almost the entire right side of an album cover. Which for me results in frequent accidental and instant scrolls to random spots in my Albums list.
Perhaps this comes from the app being a bit old and having been designed for smaller screens ?

Maybe the scrollbar touch zone should adapt to the size of the screen. Maybe its touch zone should only be located around the actual scrollbar button. Or maybe it should simply be smaller :)

To alleviate this issue, Apollo could show the current first letter of the Albums it is currently showing, like some apps do with their list: 
![ffshare-compressed](https://github.com/nuclearfog/Apollo-Music/assets/80604512/6bc04c93-2055-43a1-9993-e898040d1d70)
This example may not be the best as it's specific to contact lists (https://github.com/stephanritscher/Simple-Contacts) , but you probably get the idea.

**Comment by nuclearfog** [comment]
I have removed scrollbar from album view. I'll implement a better solution in the future.

**Comment by Cwpute** [comment]
> I have removed scrollbar from album view. I'll implement a better solution in the future.

This seems like the best and simplest solution indeed ! i am not sure if a scrollbar is useful at all in our case.

Bigger album collections may however suffer from this. Then, the alphabet scrollbar i suggested above may be the best solution yet.
