### ISSUE TITLE
Is it possible to add lyrics?

### ISSUE THREAD

**Issue by MSploof** [nuclearfog/Apollo-Music#19]
Really great app, I love it!
Thanks for continuing Apollo legacy.
But if it were possible, and not that hard could lyrics be added? It's really all I need in a music player, but I also understand if it's too hard.

**Comment by nuclearfog** [comment]
It's not difficult to implement this but I don't know where to get the lyrics. There are some online services which require a developer account.

**Comment by GSploof** [comment]
If a song has embedded lyrics, couldn't it show?

**Comment by gargamel17** [comment]
Yes, read embedded lyrics is fine

**Comment by shuvashish76** [comment]
> It's not difficult to implement this but I don't know where to get the lyrics. There are some online services which require a developer account.

Offline lyrics sync is best. We don't need internet feature just for this.
See Retro music method of doing this. https://retromusic.app/faq#collapse3

**Comment by nuclearfog** [comment]
I see no way to implement this in the future. [Lyrics Grabbr](https://github.com/illusionman1212/lyrics-grabbr) works fine with Apollo
