### ISSUE TITLE
Is this compatible with themes?

### ISSUE THREAD

**Issue by anoraktrend** [nuclearfog/Apollo-Music#2]
I'd like to know if this app is compatible with all the old Apollo themes. If not, that's fine. I'm good with the color scheme changer.

**Comment by nuclearfog** [comment]
Unfortunately it doesn't work because of new android limitations, but I will fix it in the future

**Comment by HonestAbe7** [comment]
Would love a light theme instead of dark if possible.

**Comment by Atif8413510** [comment]
> Unfortunately it doesn't work because of new android limitations, but I will fix it in the future

Can I use this code and change UI and publish app on playstore?

**Comment by nuclearfog** [comment]
yes if you change the package name

**Comment by Atif8413510** [comment]
Sure,
Thanks!

**Comment by GalaxiumNation** [comment]
> yes if you change the package name

To what exactly?

**Comment by nuclearfog** [comment]
Currently there is no way to change the theme. I have removed the old "theme implementation" because it didn't work on new Android versions.
