### ISSUE TITLE
Bluetooth  commands not working.

### ISSUE THREAD

**Issue by alexbalak21** [nuclearfog/Apollo-Music#3]
Hello,

No Bluetooth  command works on this app.
No forward, no back, no pause ?

Love the app used to use in on older versions of android.
Your version is the only one witch works with newer android versions. 
Great work !
Tell me if I can help in anyway ? I am a developer so if I can help improve my favorite music app.

**Comment by nuclearfog** [comment]
Hello,
I try to fix it, but I can't test it. There is much work, because Android changed a lot since the last Apollo release. App theme selector also doesn't work yet.
