### ISSUE TITLE
No Multi Selection 

### ISSUE THREAD

**Issue by Percherie** [nuclearfog/Apollo-Music#31]
**Describe the bug**
I have several folders to hide and you have to do it one by one. Can you add a multi-selection option?

**to reproduce**
1. Go to Floder
2. Click on folder by folder

**Smartphone (please complete the following information):**
- OS: Android 14
- App version 1.4.8

**Comment by nuclearfog** [comment]
FYI https://github.com/nuclearfog/Apollo-Music/blob/1.4.9/CONTRIBUTING.md
