### ISSUE TITLE
[BUG] Apollo doesn't work with the play/pause button on bluetooth headphones

### ISSUE THREAD

**Issue by Gersado** [nuclearfog/Apollo-Music#32]
**Describe the bug**
Apollo does nothing whenever the play/pause button on my headphones is pressed.

I've double-checked my headphones to make sure they're not broken and tested it on other music players. The headphones function properly and the other music players work with the play/pause button.

What's strange is that the headphone also has a next and previous buttons, which Apollo is able to detect them and uses those buttons as intended, it just seems like the play/pause button is the only one that Apollo doesn't work with.

**To Reproduce**
1. Connect the headphones to your device via bluetooth.
2. Once connected, open the Apollo app and play any song.
3. Let the song play for a while, then press the play/pause button on the headphones.
4. The song continues to play, when it should have been paused.
5. The opposite happens as well, if a song is paused, pressing the play/pause button will not resume the song.

**Expected behavior**
What should happen is the song should play or pause if the play/pause button is pressed.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20+ 5G
 - OS: Android 13
 - Apollo Version: 1.5.3

**Additional context**
I'm using Sony WH-CH510 headphones which I've bought a few months ago. They are in good condition and are completely functional so they are not the cause of this issue.

**Comment by nuclearfog** [comment]
I have added a fix bad26a5cd2e9c9dbe4c04b25b5d0d936a04bf495 but I can't test if it works because I don't have a Bluetooth headset. Can yout test this release ? https://github.com/nuclearfog/Apollo-Music/releases/tag/1.5.4

**Comment by Gersado** [comment]
I've installed it and sadly it's still not working. Its the same as before, the next/previous buttons work but not the play/pause button.

If it helps, here are the links to the music players I used to test my headphone buttons. Hopefully they contain clues to help fix this issue.

https://github.com/VinylMusicPlayer/VinylMusicPlayer
https://github.com/gateship-one/odyssey
https://github.com/enricocid/Music-Player-GO
https://github.com/zyrouge/symphony

**Comment by nuclearfog** [comment]
Thank you, I have tried another fix https://github.com/nuclearfog/Apollo-Music/releases/tag/1.5.4 .

**Comment by Gersado** [comment]
I installed it and sadly the results are still the same.

**Comment by Gersado** [comment]
I installed it and sadly the results are still the same.

**Comment by Gersado** [comment]
I installed it and sadly the results are still the same.

**Comment by Gersado** [comment]
I just installed the latest build on the release page, all the buttons are working correctly now. Thank you for fix this issue.

**Comment by nuclearfog** [comment]
Thank you for your help!
