### ISSUE TITLE
Differentiate dynamic and user-made playlists

### ISSUE THREAD

**Issue by Cwpute** [nuclearfog/Apollo-Music#35]
Currently, dynamic playlists are not differentiated from user-made ones, which may be confusing because they are also affected by the alphabetical ordering and get mixed up with yours.

Please introduce a way to differentiate them.
My prefered solution would be to have the dynamic ones always at the top of the list, and have them be separated from the rest wf the list by a strong line separator, or any other kind of separation.
Alternatively, they could have their text appear in italics or bold, or their font and/or background colour differ from user-made playlists.

**Comment by nuclearfog** [comment]
fyi https://github.com/nuclearfog/Apollo-Music/blob/master/CONTRIBUTING.md

**Comment by Cwpute** [comment]
Sorry, i'm not used to any sort of "developer etiquette" as i'm not one myself, just a regular user :x
So, if i wanted any feature implemented, should i just code it myself and submit a pull request ? inform you i'm doing it beforehand with an issue ? or will you not consider adding any new feature at all ? this is not clear in your document.

Le 19 juillet 2024 13:36:38 GMT+02:00, nuclearfog ***@***.***> a écrit :

**Comment by nuclearfog** [comment]
Currently I'm too busy restructuring the app and implementing this feature is much work for me. Maybe I'll implement this later.

**Comment by Cwpute** [comment]
understood 👍 keep up the good work then!
