### ISSUE TITLE
refresh playlist manually

### ISSUE THREAD

**Issue by xzs603** [nuclearfog/Apollo-Music#4]
When I download a new song, the song will add to playlist automatically. However, when I change file name of the downloaded song, the playlist couldn't auto refresh, and I didn't find a way to refresh the playlist manually(clear app data dosen't work).

**Comment by nuclearfog** [comment]
This is a common problem caused by Androids Mediastore API. Restarting Android should fix it, but I'll try to add an option to rescan media files.
