### ISSUE TITLE
[BUG] Notification doesn't show buttons right away

### ISSUE THREAD

**Issue by Cwpute** [nuclearfog/Apollo-Music#43]
**Describe the bug**
The notification doesn't show playback buttons right away : ![](https://i.postimg.cc/vHqNGgCs/Screenshot-20240718-085437-1.png)

Instead you need to pull the notification drawer down so that the buttons are shown, which takes an extra step and can get annoying : ![](https://i.postimg.cc/NfpWLP9Z/Screenshot-20240718-085457.png)

It renders these buttons useless, as opening the app from a single tap would give access to these buttons in just the same amount of interactions.

**To Reproduce**
1. Pull the notifications down
2. Butons are not shown
3. Fully pull the drawer down
4. Buttons are now accessible

**Expected behavior**
Buttons should be accesible right away without the need to pull the full drawer down.

**Smartphone (please complete the following information):**
 - OS: Android 11
 - App Version 1.5.8

**Comment by nuclearfog** [comment]
The notification layout is managed by the Android system and it is device specific. There is no way to change this. On my Android 14 emulator the media control is expanded by default: 

![1](https://github.com/user-attachments/assets/4218cacb-27e9-4f62-b41e-441864dcd896)

**Comment by Cwpute** [comment]
The problem is, on the same device and for other music players, it does appear as intended:
* Here with [Auxio](https://github.com/OxygenCobalt/Auxio) ![auxio notif](https://i.postimg.cc/52CNj6Ch/Screenshot-20240720-024607-1.png)
* With [Dialog Music Player](https://github.com/VishnuSanal/DialogMusicPlayer/releases) ![dmp notif](https://i.postimg.cc/Xv6FvMpg/Screenshot-20240720-023803-1.png)

Since these music players do have the playback buttons appear as expected, there must be something to do that would solve this issue.

**Comment by nuclearfog** [comment]
This is strange. I'll take a look at this

**Comment by nuclearfog** [comment]
I've tried a fix and it works on my phone as expected but I'm not sure if it works on other phones da4ff3b29c62ab9735887465e968204b2507b473 I'll release version 1.5.10 as soon as possible

**Comment by Cwpute** [comment]
The problem is still present for me in 1.5.10 :/

Le 30 juillet 2024 19:16:33 GMT+02:00, nuclearfog ***@***.***> a écrit :

**Comment by nuclearfog** [comment]
hopefully this 7553b93b281181c97e92ca335416e6b4e1817272 works. For me it works on my phone but I can't promise if it also works on other phones, because the design of the media control notification is device specific. I'll release version 1.5.11 after testing

**Comment by nuclearfog** [comment]
can you test the new version [1.5.11](https://github.com/nuclearfog/Apollo-Music/releases/tag/1.5.11) ?

**Comment by Cwpute** [comment]
It works now ! Congratulations :)

Le 4 août 2024 20:56:03 GMT+02:00, nuclearfog ***@***.***> a écrit :
