### ISSUE TITLE
[BUG] Error displaying file names

### ISSUE THREAD

**Issue by AlbahrawyTiger** [nuclearfog/Apollo-Music#44]
Bug in displaying file names when the device language is right to left like Arabic
![Screenshot_2024-08-03-15-46-05-44](https://github.com/user-attachments/assets/e26db1d4-d69e-4f43-be3b-322452a8b281)

**Comment by nuclearfog** [comment]
fixed: d90318cd000a5346ef2e6f1129e6370a03d98ade
