### ISSUE TITLE
Album images

### ISSUE THREAD

**Issue by uuhhhmmm** [nuclearfog/Apollo-Music#45]
Some of the albums images do not appear, this only happens on this app.

**Comment by nuclearfog** [comment]
What kind of album images do you mean? Local images or online from LastFM ? Did you try to add an image manually?

**Comment by uuhhhmmm** [comment]
> What kind of album images do you mean? Local images or online from LastFM ? Did you try to add an image manually?

local images, by adding manually do you mean on the app? i have a bunch of music and would be painful to add manually the images even if only some are missing.

**Comment by nuclearfog** [comment]
Normally the app searches for album art locally using mediastore API. Optionally you can add LastFM API key to load album arts automatically. I have tested this on different Android versions and it works. I can't fix this if I don't have more information about this problem.

**Comment by uuhhhmmm** [comment]
> Normally the app searches for album art locally using mediastore API. Optionally you can add LastFM API key to load album arts automatically. I have tested this on different Android versions and it works. I can't fix this if I don't have more information about this problem.

I don't really know what an lastfm api key is and how to use it. if you could type out some info i could get you to help me it would be great, i don't think the problem is my phone, i have tested 2 other mp3 players and they worked fine.

**Comment by nuclearfog** [comment]
I can't reproduce this bug. It's too complex to find the root cause without debugging the app code.

**Comment by uuhhhmmm** [comment]
> I can't reproduce this bug. It's too complex to find the root cause without debugging the app code.

oh ok. thanks for trying to help me anyways.
