### ISSUE TITLE
Can't Add Song To Existing Playlist

### ISSUE THREAD

**Issue by HonestAbe7** [nuclearfog/Apollo-Music#5]
Thanks for this app but I can't add songs I have to an existing playlist. Love that this app found my existing playlists too.

**Comment by nuclearfog** [comment]
Android doesn't allow editing playlist created by other apps. I can only add an option to copy a playlist to make it editable.

**Comment by nuclearfog** [comment]
I have added an option to copy an existing playlist.

**Comment by nuclearfog** [comment]
Implemented in version 1.2.4 You can now copy a foreign playlist to make it editable.
