### ISSUE TITLE
[BUG] The app does not switch tracks

### ISSUE THREAD

**Issue by userkilled** [nuclearfog/Apollo-Music#6]
The reason is that after switching to the second song, it looped it and did not switch to the next song.

**Comment by nuclearfog** [comment]
Did you check this button?

 ![IMG_20230112_213808](https://user-images.githubusercontent.com/32868976/212176273-0455034f-2839-4f39-8ffa-57245d5ae095.jpg)

**Comment by userkilled** [comment]
I check 🔀

**Comment by userkilled** [comment]
Possibly track three. When there is already a queue to play

**Comment by nuclearfog** [comment]
I have fixed this bug
